#!/usr/bin/env bash
# This script displays information about subdomains.

subdomains=("www" "lb-01" "web-01" "web-02")

domain_info ()
{
	echo -n "The subdomain $2 is a "
	dig "$1" | grep -A1 "ANSWER SECTION" | awk '/[0-9].[0-9]./ {print $4 " record and points to " $5}'

	return 0
}

if [ "$#" -eq 1 ]
then
	for sub in "${subdomains[@]}"; do
	domain_info "$sub.$1" "$sub"
	done
else
domain_info "$2.$1" "$2"
fi
