#!/usr/bin/env bash
# This script installs and configures nginx on my web server.

apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

html="/var/www/html/index.nginx-debian.html"
echo "Hello World!" > "$html"
service nginx restart
nginx -t
nginx -s reload
