#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine to these requirements:
# The page must return an HTTP 404 error code.
# The page must contain the string "Ceci n'est pas une page".

apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

html="/var/www/html/index.nginx-debian.html"
echo "Hello World!" > "$html"

config="/etc/nginx/sites-available/default"
requirement="\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/x.com\/IAshimonye83170;\n\t}\n}"
sed -i -r "s/^}$/$requirement/" "$config"

error_html="/var/www/html/404.html"
echo "Ceci n'est pas une page" > "$error_html"
error_requirement="\n\terror_page 404 \/404.html;\n\tlocation \/404.html {\n\t\tinternal;\n\t}\n}"
sed -i -r "s/^}$/$error_requirement/" "$config"

service nginx restart
nginx -t
nginx -s reload
