#!/usr/bin/env bash
# This script transfers a file from our client to a server.

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less"
else
	if [ -n "$4" ]; then
		scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username"@"$ip":~/
	else
	       scp -o StrictHostKeyChecking=no -i "$path_to_file" "$username"@"$ip":~/
	fi
fi
