#!/usr/bin/env bash
# This script pings (5 times) an IP address passed as an argument.
if [ "$1" = "" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping "$1"
	ping "$1"
	ping "$1"
	ping "$1"
	ping "$1"
fi
