#!/usr/bin/env bash
#  This script installs Nginx and configures it to listen
#+ on port 80 of all the server's active IPv4 IPs.

apt-get -y update
apt-get -y install nginx

rm -rf /etc/nginx/sites-enabled/
ln -s /etc/nginx/sites-available/ /etc/nginx/sites-enabled/

service nginx start
