#!/usr/bin/env bash
#  This script installs Nginx and configures it to listen
#+ on port 80 of all the server's active IPv4 IPs.

server_config="
server {
	listen 80 default_server; 
	listen [::]:80 default_server;

	root /usr/share/nginx/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}
}
"
echo "$server_config" > /etc/nginx/sites-enabled/default

service nginx restart
