#!/usr/bin/env bash
# This script configures an Ubuntu server, changing the Localhost
# and Facebook IPs. 
cp /etc/hosts ~/hosts.new
facebook=$(grep facebook.com ~/hosts.new)
if [ -z "$facebook" ]
then
	sed -i 's/.*\slocalhost$/127.0.0.2\tlocalhost\n8.8.8.8\t\tfacebook.com/' ~/hosts.new
else
	sed -i 's/.*\slocalhost$/127.0.0.2\tlocalhost/' ~/hosts.new
	sed -i 's/.*\sfacebook.com$/8.8.8.8\t\tfacebook.com/' ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts
