#!/usr/bin/env bash
# this script fixes this container so that "nginx" is running as the nginx user.

sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user www-data/" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill nginx
pkill apache2
sudo -u nginx service nginx start
